#include "special.h"
#include "util_defines.h"

#define CONFIG_ROOT_VIEWS_DEFINITIONS_1(vnt, vnl) UTIL_CONCAT(TYPE_ROOT_APP,vnt,View) *UTIL_CONCAT(vnl,_view);
#define CONFIG_ROOT_VIEWS_DEFINITIONS UTIL_FOR_EACH_MACRO_2_ARGS(CONFIG_ROOT_VIEWS_DEFINITIONS_1, VIEWS_T_L_ALL)

#define CONFIG_ROOT_VIEWS_ALLOC_1(vnl) \
    UTIL_EXPAND(VARIABLE_ROOT_APP)->UTIL_CONCAT(vnl,_view) = UTIL_CONCAT(VARIABLE_ROOT_APP,_,vnl,_view_alloc();)
#define CONFIG_ROOT_VIEWS_ALLOC UTIL_FOR_EACH_MACRO(CONFIG_ROOT_VIEWS_ALLOC_1, VIEWS_L_ALL)

#define CONFIG_ROOT_ADD_VIEWS_(vnt,vnl) \
    gif_application_add_view( \
        VARIABLE_ROOT_APP->app, \
        UTIL_CONCAT(TYPE_ROOT_APP,View,vnt), \
        VARIABLE_ROOT_APP->UTIL_CONCAT(vnl,_view)->view);
#define CONFIG_ROOT_ADD_VIEWS UTIL_FOR_EACH_MACRO_2_ARGS(CONFIG_ROOT_ADD_VIEWS_, VIEWS_T_L_ALL)

#define CONFIG_VIEWS_VIEWS_ENUM_(vnt) UTIL_CONCAT(TYPE_ROOT_APP,View,vnt),
#define CONFIG_VIEWS_VIEWS_ENUM UTIL_FOR_EACH_MACRO(CONFIG_VIEWS_VIEWS_ENUM_,VIEWS_T_ALL)

#define VIEW_INIT void _auto_view_init
#define CUSTOM_MODEL_NAME MODEL_S
