// This file was automatically generated by GIF.
// DO NOT EDIT UNLESS YOU KNOW WHAT YOU ARE DOING
#include "util_defines.h"
#define APP_NAME_L app_name_l
#define APP_NAME_U app_name_u
#define APP_NAME_T app_name_t
#define VIEWS_L_ALL views_all_l
#define VIEWS_U_ALL views_all_u
#define VIEWS_T_ALL views_all_t
#define VIEWS_T_L_ALL views_alt__

#define VIEWS_FIRST_L view_first_l
#define VIEWS_FIRST_U view_first_u
#define VIEWS_FIRST_T view_first_t
#define TYPE_ROOT_APP UTIL_CONCAT(APP_NAME_T,App)
#define VARIABLE_ROOT_APP UTIL_CONCAT(APP_NAME_L,_app)
#define VIEWS_ENUM_TYPE UTIL_CONCAT(TYPE_ROOT_APP,Event)
